[project]
name = "emilyprime"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "haystack-ai>=2.8.0",
    "sentence-transformers>=3.0.0",
]
